CateringOrders/CateringOrders/Controllers/DailyMenuController.cs
using CateringOrders.BLL.Services.Implementations;
using CateringOrders.BLL.Services.Interfaces;
using CateringOrders.Controllers;
using CateringOrders.Data.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CateringOrders.Controllers
{
    public class DailyMenuController : Controller
    {

        private readonly IDailyMenuService _dailyMenuService;
        private readonly IFoodItemsService _foodItemsService;

        public DailyMenuController(IDailyMenuService dailyMenuService, IFoodItemsService foodItemsService)
        {
            _dailyMenuService = dailyMenuService ?? throw new ArgumentNullException(nameof(dailyMenuService));
            _foodItemsService = foodItemsService;
        }

        public async Task<IActionResult> Index()
        {
            var resultTotal = await _dailyMenuService.GetAll();

            return View(resultTotal);

        }

        //Breakpoint, new Implementations added for DailyMenuController
        public async Task<ActionResult> Create(string searchString)
        {
            var foodList = await _foodItemsService.GetAll(searchString);
            ViewBag.FoodList = new SelectList(foodList, "Id", "Name");
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(DailyMenu dailyMenu)
        {
            var result = await _dailyMenuService.Create(dailyMenu);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<ActionResult> Delete(int id)
        {
            var softDelete = await _dailyMenuService.DeleteAsync(id);
            return View(softDelete);
        }

        [HttpPost]
        public async Task<ActionResult> DeleteAsync(int id)
        {
            await _dailyMenuService.DeleteAsync(id);
            return RedirectToAction("Index");
        }

    }

}

CateringOrders/CateringOrders/Controllers/EmployeeOrdersController.cs
using CateringOrders.BLL.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace CateringOrders.Controllers;

public class EmployeeOrdersController : Controller
{
	private readonly IEmployeeOrdersService _employeeOrdersService;

	public EmployeeOrdersController(IEmployeeOrdersService employeeOrdersService)
	{
		_employeeOrdersService = employeeOrdersService ?? throw new ArgumentNullException(nameof(employeeOrdersService));
	}

	public async Task<IActionResult> Index()
	{
		var resultTotal = await _employeeOrdersService.GetAll();

		return View(resultTotal);

	}
}

CateringOrders/CateringOrders/Controllers/FoodCategoryController.cs
using CateringOrders.BLL.Services.Interfaces;
using CateringOrders.Data.Repositories.Implementations;
using Microsoft.AspNetCore.Mvc;

namespace CateringOrders.Controllers;

public class FoodCategoryController : Controller
{
    private readonly IFoodCategoryService _foodCategoryService;

    public FoodCategoryController(IFoodCategoryService foodCategoryService)
    {
        _foodCategoryService = foodCategoryService ?? throw new ArgumentNullException(nameof(foodCategoryService));
    }

    public async Task<IActionResult> Index()
    {
        var resultTotal = await _foodCategoryService.GetAll();

        return View(resultTotal);

    }
}

CateringOrders/CateringOrders/Controllers/FoodItemsController.cs
using CateringOrders.BLL.Services.Interfaces;
using CateringOrders.Data.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Security.Policy;

namespace CateringOrders.Controllers;

public class FoodItemsController : Controller
{
    private readonly IFoodItemsService _foodItemsService;
    private readonly IFoodCategoryService _foodCategoryService;

    public FoodItemsController(IFoodItemsService foodItemsService, IFoodCategoryService foodCategoryService)
    {
        _foodItemsService = foodItemsService ?? throw new ArgumentNullException(nameof(foodItemsService));
        _foodCategoryService = foodCategoryService ?? throw new ArgumentNullException(nameof(_foodCategoryService));
    }

    public async Task<IActionResult> Index()
    {
        var resultTotal = await _foodItemsService.GetAll();
        return View(resultTotal);
    }
    public async Task<ActionResult> Create()
    {
        var foodCategories = await _foodCategoryService.GetAll();
        ViewBag.FoodCategories = foodCategories;
        return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(FoodItems foodItems)
    {
        var result = await _foodItemsService.Create(foodItems);

        return RedirectToAction("Index");
    }

    [HttpGet]
    public async Task<ActionResult> Delete(int id)
    {
        var softDelete = await _foodItemsService.DeleteAsync(id);
        return View(softDelete);
    }

    [HttpPost]
    public async Task<ActionResult> DeleteAsync(int id)
    {
        await _foodItemsService.DeleteAsync(id);
        return RedirectToAction("Index");
    }

    public async Task<IActionResult> Edit(int Id)
    {

        var foodItems = await _foodItemsService.GetAsync(Id);
        if (foodItems == null)
        {
            return NotFound();
        }

        var foodItems = await _foodItemsService.GetAll();
        ViewBag.CategoryId = new SelectList(foodItems, "Id", "Name", booking.CategoryId);

        return View(booking);
    }

    [HttpPost]
    public async Task<ActionResult> Edit(FoodItems foodItems)
    {

        await _foodItemsService.Edit(foodItems);
        return RedirectToAction("Index");

    }
}

CateringOrders/CateringOrders/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Tasty - Catering</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CateringOrders.styles.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Smokum&display=swap" rel="stylesheet">
    <style>
        .mainName{
            font-size: 35px;
            margin: 0;
            padding: 0;
            font-family: 'Smokum', cursive;
        }
        #mainMenu {
            font-size: 22px;
            margin: 0;
            padding: 0;
            font-family: "Cormorant Garamond", Georgia, serif;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand mainName" asp-area="" asp-controller="Home" asp-action="Index">Tasty Catering</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div id="mainMenu" class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FoodItems" asp-action="Index">Food Items</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DailyMenu" asp-action="Index">Daily Menu</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="EmployeeOrders" asp-action="Index">Employee Orders</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FoodCategory" asp-action="Index">Food Categories</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Tasty Catering - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>